Maxima.Web/Areas/Admin/Controllers/AdditionalImgController.cs
using Maxima.DataAccess.Repository.IRepository;
using Maxima.Models;
using Microsoft.AspNetCore.Mvc;

namespace Maxima.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdditionalImgController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;

        public AdditionalImgController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            IEnumerable<AdditionalImg> objAdditionalImgList = _unitOfWork.AdditionalImg.GetAll();
            return View(objAdditionalImgList);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AdditionalImg obj, IFormFile? PostedFile)

        {

            if (ModelState.IsValid)
            {

                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (PostedFile != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\products");
                    var extension = Path.GetExtension(PostedFile.FileName);

                    if (obj.AdditionalImgUrl != null)
                    {
                        var oldImagePath1 = Path.Combine(wwwRootPath, obj.AdditionalImgUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath1))
                        {
                            System.IO.File.Delete(oldImagePath1);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        PostedFile.CopyTo(fileStreams);
                    }
                    obj.AdditionalImgUrl = @"\images\products\" + fileName + extension;

                }


                _unitOfWork.AdditionalImg.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "AdditionalImg created successfully";
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var additionalImgFromDbFirst = _unitOfWork.AdditionalImg.GetFirstOrDefault(u => u.Id == id);

            if (additionalImgFromDbFirst == null)
            {
                return NotFound();
            }

            return View(additionalImgFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(AdditionalImg obj)
        {            
            if (ModelState.IsValid)
            {
                _unitOfWork.AdditionalImg.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "AdditionalImg updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var additionalImgFromDbFirst = _unitOfWork.AdditionalImg.GetFirstOrDefault(u => u.Id == id);

            if (additionalImgFromDbFirst == null)
            {
                return NotFound();
            }

            return View(additionalImgFromDbFirst);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.AdditionalImg.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.AdditionalImg.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "AdditionalImg deleted successfully";
            return RedirectToAction("Index");

        }
    }


}

Maxima.Web/Areas/Admin/Controllers/ProductController.cs
using Maxima.DataAccess.Repository.IRepository;
using Maxima.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Maxima.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {

            return View();
        }

        //GET
        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
            {
                Product = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),

                AdditionalImgList = _unitOfWork.AdditionalImg.GetAll(i => i.TovarId == id),

                SizeList = _unitOfWork.Size.GetAll(i => i.TovarId == id),

            };

            if (id == null || id == 0)
            {
                return View(productVM);
            }
            else
            {
                productVM.Product = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
                return View(productVM);

            }


        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj, IFormFile? file)
        {

            if (ModelState.IsValid)
            {

                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\products");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.Product.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.Product.ImageUrl = @"\images\products\" + fileName + extension;

                }
                if (obj.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(obj.Product);

                }
                else
                {
                    _unitOfWork.Product.Update(obj.Product);

                }

                _unitOfWork.Save();

                TempData["success"] = $"Product created successfully {obj.Product.Id}";
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitOfWork.Product.GetAll(includeProperties: "Category");
            return Json(new { data = productList });
        }

        //POST
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _unitOfWork.Product.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });

        }
        #endregion

    }
}

Maxima.Web/Areas/Admin/Controllers/SizeController.cs
using Maxima.DataAccess.Repository.IRepository;
using Maxima.Models;
using Microsoft.AspNetCore.Mvc;

namespace Maxima.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SizeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public SizeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Size> objSizeList = _unitOfWork.Size.GetAll();
            return View(objSizeList);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Size obj)
        {
            if (obj.Name == obj.Count.ToString())
            {
                ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name.");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Size.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Size created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var sizeFromDbFirst = _unitOfWork.Size.GetFirstOrDefault(u => u.Id == id);

            if (sizeFromDbFirst == null)
            {
                return NotFound();
            }

            return View(sizeFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Size obj)
        {
            if (obj.Name == obj.Count.ToString())
            {
                ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name.");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Size.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Size updated successfully";
                return RedirectToAction("Index");
            }
                       
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var sizeFromDbFirst = _unitOfWork.Size.GetFirstOrDefault(u => u.Id == id);

            if (sizeFromDbFirst == null)
            {
                return NotFound();
            }

            return View(sizeFromDbFirst);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.Size.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.Size.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Size deleted successfully";
            return RedirectToAction("Index");

        }
    }
}

Maxima.Web/Areas/Admin/Views/Product/Index.cshtml
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-9">
           <p class="product_card_secondary_text text-uppercase">
           products
        </p>
		</div>
        <div class="col-3 top-0 end-0">
            <a asp-controller="Product" asp-action="Upsert" class="btn btn-continue text-uppercase">
                Create new Product
			</a>
		</div>
	</div>
    <br /><br />

<table  id="tblData"  class="table table-striped table-hover" style="width:100%">
    <thead>
        <tr>
            <th ></th>
            <th class="product_card_main_text text-uppercase">Name</th>           
            <th class="product_card_main_text text-uppercase">Price</th>
            <th class="product_card_main_text text-uppercase">Category</th>            
            <th></th>
		</tr>
	</thead>
</table>
</div>

@section Scripts{
    <script src="~/js/product.js"></script>
}

Maxima.Web/Areas/Admin/Views/Product/Upsert.cshtml
@model Maxima.Models.ViewModels.ProductVM

<form method="post" asp-action="Upsert" enctype="multipart/form-data">
    <input asp-for="Product.Id" hidden />

    <div class="row">
        <div class="col-10 m-2">
            <p class="product_card_secondary_text text-uppercase">@(Model.Product.Id!=0?"Update": "Create")  Product</p>
        </div>
    </div>

    <div class="row ">
        <div class="col-3 ">
            <div class="m-2 col-12 product_card_main_text text-uppercase col-4">
                <label asp-for="Product.Name"></label>
                <input asp-for="Product.Name" class="form-control" />
                <span asp-validation-for="Product.Name" class="text-danger"></span>
            </div>

            <div class="m-2 col-12 product_card_main_text text-uppercase col-4">
                <label asp-for="Product.Price"></label>
                <input asp-for="Product.Price" class="form-control" />
                <span asp-validation-for="Product.Price" class="text-danger"></span>
            </div>

            <div class="m-2 pt-4 col-12 product_card_main_text text-uppercase">
                <label asp-for="Product.ImageUrl"></label>
                <input type="file" id="uploadBox" name="file" class="form-control" />
            </div>

            <div class="m-2 col-12 product_card_main_text text-uppercase">
                <label asp-for="Product.CategoryId"></label>
                <select asp-for="Product.CategoryId" asp-items="@Model.CategoryList" class="form-select text-uppercase product_card_secondary_text">
                    <option disabled selected>--Select Category--</option>
                </select>
                <span asp-validation-for="Product.CategoryId" class="product_card_accent_text"></span>
            </div>

            <div class="m-2 pt-4 col-12 product_card_main_text text-uppercase col-4">
                <label asp-for="Product.ShortDesc"></label>
                <textarea asp-for="Product.ShortDesc" rows="3" class="form-control"></textarea>
                <span asp-validation-for="Product.ShortDesc" class="text-danger"></span>
            </div>

            <div class="m-2 col-12 product_card_main_text text-uppercase col-4">
                <label asp-for="Product.Description"></label>
                <textarea asp-for="Product.Description" rows="3" class="form-control"></textarea>
                <span asp-validation-for="Product.Description" class="text-danger"></span>
            </div>


            <div class="m-2 col-12 mt-4">
                @if (Model.Product.Id != 0)
                {
                    <button type="submit" class="btn btn-continue text-uppercase " style="width:150px">Update</button>
                }
                else
                {
                    <button type="submit" onclick="return ValidateInput()" class="btn btn-continue text-uppercase " style="width:150px">Create</button>
                }
                <a asp-controller="Product" asp-action="Index" class="btn btn-continue text-uppercase " style="width:150px">
                    Back
                </a>
            </div>
        </div>

        <div class="col-3 d-flex justify-content-center">
            <div class="m-2 ">
                <img src="@Model.Product.ImageUrl"
                     width="100%" />
            </div>
        </div>

        <div class="col-6 ">
            @if (Model.Product.Id != 0)
            {
                <div class="m-2">
                    <a asp-controller="AdditionalImg" asp-action="Create" asp-route-tovarid="@Model.Product.Id" class="btn btn-filter text-uppercase">
                        ADD new Image
                    </a>
                </div>
            }

            <div class="m-2 row position-relative">
                @foreach (var item in Model.AdditionalImgList)
                {
                    <div class="col-4 m-0">
                        <div class="card card-body border-0 rounded-0" style="background: #BFB1B1">
                            <img src="@item.AdditionalImgUrl" class="img-fluid">
                            <a asp-controller="AdditionalImg" asp-action="Edit" asp-route-id="@item.Id" class=" btn btn-continue text-uppercase mt-2">
                                Edit
                            </a>
                        </div>
                    </div>
                }
            </div>

            @if (Model.Product.Id != 0)
            {
                <div class="m-2">
                    <a asp-controller="Size" asp-action="Create" asp-route-tovarid="@Model.Product.Id" class="btn btn-filter text-uppercase">
                        Add Size
                    </a>
                </div>

            }

            <div class="m-2 row position-relative">
                @foreach (var item in Model.SizeList)
                {
                    <div class="col-2 p-2 mt-2">
                        <div class="card card-body p-0 border-0 rounded-0" style="background: #BFB1B1">
                            <div class="">
                                <a class="btn btn-filter product_card_secondary_text position-absolute top-0 end-0" role="button" style="color: #47343F" asp-controller="Size"
                               asp-action="Delete" asp-route-id="@item.Id">
                                    <i style="font-size:small;" class="bi bi-trash-fill"></i>
                                </a>
                                <a class="btn btn-filter product_card_secondary_text position-absolute top-0 start-0" role="button" style="color: #47343F" asp-controller="Size"
                               asp-action="Edit" asp-route-id="@item.Id">
                                    <i style="font-size:small;" class="bi bi-pencil-square"></i>
                                </a>
                            </div>

                            <div class="row m-1 pt-5">
                                <p class="col-7 ">
                                    <input asp-for="@item.DisplayName" disabled="disabled" class="bg-transparent border-0 product_card_secondary_text" />
                                    <span asp-validation-for="@item" class="product_card_accent_text"></span>
                                </p>
                                <p class="col-2 ">
                                    <input asp-for="@item.Count" disabled="disabled" class="bg-transparent border-0 product_card_accent_text" />
                                    <span asp-validation-for="@item" class="product_card_accent_text"></span>
                                </p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</form>

@section Scripts{
	@{
	<partial name="_ValidationScriptsPartial" />
	}
<script>
    tinymce.init({
      selector: 'textarea',
      plugins: 'advlist autolink lists link image charmap print preview hr anchor pagebreak',
      toolbar_mode: 'floating',
   });
  
	function ValidateInput(){
		if(document.getElementById("uploadBox").value==""){
			Swal.fire({
			  icon: 'error',
			  title: 'Oops...',
			  text: 'Please upload an Image!',
			});
			return false;
		}
		return true;
	}
</script>
}